<?php if ($block->getConfigValue("sxFrontendActive")) : ?>
    <script type="text/javascript">
        if (typeof sxSearchAvailable === 'undefined') {
            sxSearchAvailable = true;
        }

        if (sxSearchAvailable) {
            /* eslint-disable */
            (function() {
                var siteId = '<?= $block->getConfigValue("projectId") ?>'; // the project id
                window.ss360Config = {
                    siteId: siteId,
                    baseUrl: '<?= $block->getConfigValue("apiUrl") ?>search?projectId=' + siteId + '&userGroup=<?= $block->getConfigValue("userGroup") ?>',
                    suggestBaseUrl: '<?= $block->getConfigValue("apiUrl") ?>search/suggestions?projectId=' + siteId + '&userGroup=<?= $block->getConfigValue("userGroup") ?>',
                    searchBox: {
                        selector: 'input[name="q"]', // search box css selector
                        searchButton: 'button.action.search', // search button css selector (makes the search suggestions extend over the full search form width)
                        preventFormParentSubmit: false // prevents the search plugin from preventing search form submit
                    },
                    results: {
                        ignoreEnter: true // search plugin will ignore enter keys (won't submit search on enter)
                    },
                    callbacks: {
                        preSearch: function(query) { // handle query suggestions
                            var searchForm = document.getElementsByName('search')[0];
                            var searchBox = document.getElementsByName('search')[0];
                            searchBox.value = query;
                            searchForm.submit();
                            return false; // prevent search
                        }
                    }
                };
                var e = document.createElement('script');
                e.src = 'https://cdn.sitesearch360.com/v13/sitesearch360-v13.min.js';
                document.getElementsByTagName('body')[0].appendChild(e);
            }());

            var mageAutoSuggestion = document.getElementById('search_autocomplete');
            if (mageAutoSuggestion !== null) {
                mageAutoSuggestion.remove();
            }
        }
    </script>
    <script type="text/javascript">
        require(['noUiSlider'], function(noUiSlider) {

            var sliders = document.getElementsByClassName('sxRangeFilter');

            for (var i = 0; i < sliders.length; i++) {

                sliders[i].parentNode.getElementsByClassName('start')[0].value = sliders[i].getAttribute('data-start');
                sliders[i].parentNode.getElementsByClassName('end')[0].value = sliders[i].getAttribute('data-end');

                noUiSlider.create(sliders[i], {
                    start: [sliders[i].getAttribute('data-start'), sliders[i].getAttribute('data-end')],
                    connect: true,
                    range: {
                        'min': parseFloat(sliders[i].getAttribute('data-range-min')),
                        'max': parseFloat(sliders[i].getAttribute('data-range-max'))
                    }
                });

                sliders[i].noUiSlider.on('update', function(values, handle) {
                    //console.log(this.target);
                    this.target.parentNode.getElementsByClassName('start')[0].value = values[0];
                    this.target.parentNode.getElementsByClassName('end')[0].value = values[1];
                });

                sliders[i].noUiSlider.on('end', function(values, handle) {
                    url = this.target.getAttribute('data-url') + values[0] + '___' + values[1];
                    window.location.href = url;
                });

                sliders[i].parentNode.getElementsByTagName('button')[0].addEventListener('click', function(event) {

                    sliderWrapper = event.target.parentNode.parentNode;

                    min = sliderWrapper.getElementsByClassName('start')[0].value;
                    max = sliderWrapper.getElementsByClassName('end')[0].value;

                    url = sliderWrapper.getElementsByClassName('sxRangeFilter')[0].getAttribute('data-url') + min + '___' + max;
                    window.location.href = url;

                }, false);

            };
        });
    </script>
<?php endif; ?>
<script type="text/javascript">
    console.info('SiteSearch360 Magento2-Module: Version <?= $block->getExtensionVersion() ?>');
</script>